# This is a basic workflow to help you get started with Actions

name: Build And Deploy Demo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAR_NAME: demo.jar
      SCP_SRC: ./target/demo.jar
      TAR_STRIP_PATH: 1
      SCP_TAR_DIR: ~/demo
      RUNTIME_DIR: /var/todolist
      SERVICE_NAME: demo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master


    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        wd=`pwd`
        echo "we are at "$wd
    - name: Check jdk
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - name: mvn prepare
      id: mvn_cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}

    - name: build
      run: |
        wd=`pwd`
        echo "we are at "$wd
        mvn -B clean package

    - name: test existance
      run: |
        wd=`pwd`
        echo "we are at "$wd
        cd target
        ls

    - name: ssh before scp
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.CI_HOST }}
        port: ${{ secrets.CI_SSH_PORT }}
        username: ${{ secrets.CI_USER }}
        key: ${{ secrets.CI_SSH_KEY }}
        script: |
          mkdir -p ${{env.SCP_TAR_DIR}}

    - name: send file by scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CI_HOST }}
        username: ${{ secrets.CI_USER }}
        port: ${{ secrets.CI_SSH_PORT }}
        key: ${{ secrets.CI_SSH_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_port: ${{ secrets.PROXY_SSH_PORT }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_password: ${{ secrets.PROXY_PASSWORD }}
        proxy_key: ${{ secrets.PROXY_SSH_KEY }}
        source: ${{env.SCP_SRC}}
        target: ${{env.SCP_TAR_DIR}}
        strip_components: ${{env.TAR_STRIP_PATH}}

    - name: ssh after scp (run server)
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.CI_HOST }}
        port: ${{ secrets.CI_SSH_PORT }}
        username: ${{ secrets.CI_USER }}
        key: ${{ secrets.CI_SSH_KEY }}
        script: |
          cd ${{env.SCP_TAR_DIR}}
          JarFile=${{env.JAR_NAME}}
          TarDir=${{env.RUNTIME_DIR}}
          echo "make dir $TarDir if exists"
          sudo mkdir -p $TarDir
          echo "copy $JarFile to $TarDir"
          sudo cp ${{env.SCP_TAR_DIR}}/$JarFile $TarDir
          sudo chmod 777 $TarDir/*
          cd /lib/systemd/system
          if [ -e demo.service ];
          then
              echo "demo.service exists. stop it"
              sudo systemctl stop demo;
              echo "remove it";
              sudo rm demo.service;
          fi;
          echo "write service"
          sudo touch ${{env.SERVICE_NAME}}.service;
          echo "[Unit]" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "Description=demo" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "After=syslog.target" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "[Service]" | sudo tee -a demo.service;
          echo "User=root" | sudo tee -a demo.service;
          echo "ExecStart=$TarDir/$JarFile" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "SuccessExitStatus=143" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "[Install]" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "WantedBy=multi-user.target" | sudo tee -a ${{env.SERVICE_NAME}}.service;
          echo "reload service";
          sudo systemctl daemon-reload;
          echo "start service";
          sudo systemctl start ${{env.SERVICE_NAME}};
