name: Test My Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: call my action
        id: callMyAction
        run: |
          echo "GitHub Ref="${GITHUB_REF}
