name: Test My Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: call my action
      id: callMyAction
      uses: discko/MavenAndDeploy
      with:
        java-version: 1.8

    - name: show output
      run: |
        echo "the output is "${{steps.callMyAction.outputs.result}}
