name: Test My Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ master ]

env:
  profile: "test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: call my action
        id: callMyAction
        run: |
          echo "GitHub Ref="$GITHUB_REF
          echo "current profile:"$profile
      
      - name: check if dev
        if: ${{ endsWith( github.ref , '/dev' ) }}
        run: |
          echo "profile=dev" >> $GITHUB_ENV
          echo "set profile to dev"
      
      - name: check if master
        if: endsWith( ${{github.ref}}, '/master')
        run: |
          echo "profile=product" >> $GITHUB_ENV
          echo "set profile to product"
      
      - name: show profile
        run: echo "new profile:"$profile
